### ISSUE TITLE
HR Pacing app will not stay open

### ISSUE THREAD

**Issue by Gloaming2003** [baydevelopments/support#2]
I just bought a Versa 2 for the express purpose of using this app. I have severe ME/CFS, and I am steadily getting worse. Unfortunately, the app does not stay open on my watch. I have the always on display set, and I think I have the app set up correctly. It shows on my phone, at least. Every time the app closes, I have to set up all the numbers again. Sometimes the fitbit gets it, and sometimes not. I've done this A LOT trying to get this to work. My current crash is getting worse because I'm spending so much time spinning my wheels on this app. I'm about to buy another Versa 2 so I can throw them both away. Can you please help? I also emailed you earlier today and tagged you on a few YouTube comments over the past week. I'm trying every way possible in hopes that I don't have to make my husband drive the 2.5 hour round trip to return the Versa 2 to Walmart. Please help!

**Comment by Gloaming2003** [comment]
Hi, again! I went ahead and bought a Versa 3 and had it overnighted to me. I will update this once I test the app out to see if it works. Thanks!

**Comment by Gloaming2003** [comment]
Sorry, I didn't mean to close the ticket. Brain fog. Lol

**Comment by Gloaming2003** [comment]
Tested it, and it works like a charm! Plus, I found the refurbished Versa 3, sent overnight FedEx, for $31.99 on eBay, so my husband can return the $129.99 one he got at Walmart, and we ended up saving almost $100. Amazing how karma can work sometimes, right? I hope you have a great weekend!

**Comment by allyann** [comment]
Sorry I have been in a bad crash. I hope it is working for you now. There
was an issue with the Versa 2 settings out of the factory and it needed to
update the Fitbit App on your phone to trigger an update on the watch.

Please let me know if there is any other issues .

Allyann

**Comment by Gloaming2003** [comment]
Thanks so much for the email! I actually checked your tickets page first.
I'm in a bad crash right now, and email didn't occur to me.  Lol

We bought a refurbished Versa 3 on eBay, sent overnight to us, for only
$31.99. It works perfectly. I never realized my heart rate was going so
high. Great app!

Take care
Angie

**Comment by allyann** [comment]
Thank you :)
